language: ruby
rvm:
- 2.0.0-p481
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: cJz2NgXA36cZriGC5/tfETlnIKTb3v3lJI3T5jR3aEls1BPe6Ivo0N7TIBdXf6q4lg8WAc1IBMiJWgvngk7G4YXHU0oQy3PGmp7UtCj1zzg2B2Y9SEO+dF4y2XJls2NW5z0Fu1pA5jyxyBS+v/JAYGHjyaKjXORjEaj1y+NeEwQ=
  app: travis-test-app
  run:
    - "rake db:migrate"
    - restart